from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

def generate_assessment_pdf(assessment, user):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Equipment Recommendation Report", styles["Title"]))
    elements.append(Spacer(1,20))

    elements.append(Paragraph("Generated By", styles["Heading2"]))
    elements.append(Paragraph(f"Doctor Name: {user.name}", styles["Normal"]))
    elements.append(Paragraph(f"Email: {user.email}", styles["Normal"]))
    if hasattr(user, 'role') and user.role:
        elements.append(Paragraph(f"Role: {user.role}", styles["Normal"]))
    elements.append(Paragraph(f"Generated At: {assessment.created_at.strftime('%Y-%m-%d %H:%M:%S') if assessment.created_at else 'N/A'}", styles["Normal"]))

    elements.append(Spacer(1,20))

    patient = assessment.patient

    elements.append(Paragraph(f"Patient Name: {patient.get('name', 'Unknown')}", styles["Normal"]))
    elements.append(Paragraph(f"Age: {patient.get('age', 'Unknown')}", styles["Normal"]))
    elements.append(Spacer(1,20))

    for section_name, section in assessment.output_data.items():
        elements.append(Paragraph(section_name.replace("_", " ").title(), styles["Heading2"]))

        if section.get("equipment"):
            elements.append(Paragraph("Equipment", styles["Heading3"]))
            for item in section["equipment"]:
                elements.append(Paragraph(f"• {item}", styles["Normal"]))

        elements.append(Spacer(1,10))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
