from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_assessment_pdf(assessment, user):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer)
    styles = getSampleStyleSheet()
    
    # Custom bold styling for subheadings
    if "Bold" not in styles:
        styles.add(ParagraphStyle(name="Bold", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=11, spaceAfter=6, spaceBefore=6))
    
    elements = []

    # Title & Subtitle
    elements.append(Paragraph("Equipment Recommendation Report", styles["Title"]))
    elements.append(Paragraph("Eldersmiles Discharge Triage Assessment", styles["Heading2"]))
    elements.append(Spacer(1, 15))

    # Patient Summary
    patient = assessment.patient if assessment.patient else {}
    elements.append(Paragraph("Patient Summary", styles["Heading3"]))
    elements.append(Paragraph(f"Patient Name: {patient.get('name', 'Unknown')}", styles["Normal"]))
    elements.append(Paragraph(f"Age: {patient.get('age', 'Unknown')}", styles["Normal"]))
    if patient.get("discharge_date"):
        elements.append(Paragraph(f"Discharge Date: {patient.get('discharge_date')}", styles["Normal"]))
    elements.append(Spacer(1, 15))

    # Generated By
    elements.append(Paragraph("Generated By", styles["Heading3"]))
    elements.append(Paragraph(f"Doctor Name: {user.name}", styles["Normal"]))
    elements.append(Paragraph(f"Email: {user.email}", styles["Normal"]))
    if hasattr(user, 'role') and user.role:
        elements.append(Paragraph(f"Role: {user.role}", styles["Normal"]))
    
    created_str = assessment.created_at.strftime('%Y-%m-%d %H:%M:%S') if getattr(assessment, 'created_at', None) else 'N/A'
    elements.append(Paragraph(f"Generated At: {created_str}", styles["Normal"]))
    elements.append(Spacer(1, 20))

    # Assessment Categories in Specific Order
    categories = [
        "mobility",
        "feeding",
        "elimination",
        "respiratory",
        "pressure_injury",
        "wound_care",
        "home_environment",
        "cognitive"
    ]

    output_data = assessment.output_data if assessment.output_data else {}

    for cat in categories:
        if cat in output_data:
            section = output_data[cat]
            if not isinstance(section, dict):
                continue

            # Section Title
            elements.append(Paragraph(cat.replace("_", " ").title(), styles["Heading2"]))
            
            # Equipment List
            equipment = section.get("equipment")
            if equipment and isinstance(equipment, list) and len(equipment) > 0:
                elements.append(Paragraph("Equipment", styles["Bold"]))
                for item in equipment:
                    elements.append(Paragraph(f"• {item}", styles["Normal"]))
            
            # Care Instructions
            instructions = section.get("care_instructions")
            if instructions:
                elements.append(Paragraph("Care Instructions", styles["Bold"]))
                elements.append(Paragraph(f"{instructions}", styles["Normal"]))
            
            elements.append(Spacer(1, 15))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
